name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before you hit the submit button:
          * Please see our [Contribution Guidelines](https://github.com/nitis-languages/runtime/blob/master/CONTRIBUTING.md).
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please share a clear and concise description of the issue and optionally provide reproducibility information and output.
      placeholder: Description
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      multiple: true
      options:
        - Not specified / possibly all
        - Windows
        - Linux
        - Android
        - Other
  - type: dropdown
    id: target-architecture
    attributes:
      label: Architecture
      multiple: true
      options:
        - Not specified
        - X86_64 (AMD64)
        - Other
